# Generated by Django 4.0.4 on 2022-04-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_place_options_alter_placeimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='place',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
